install.packages("tidyverse")
install.packages("ragg")
install.packages("svglite")
install.packages("ggrepel")
install.packages("ggh4x")
install.packages("patchwork")
install.packages("ggnewscale")
install.packages("VennDiagram")
install.packages("treemap") ## optional
install.packages("BiocManager")
renv::install("bioc::DESeq2@1.30.1")
renv::install("bioc::apeglm@1.12.0")
renv::install("bioc::clusterProfiler@3.18.1")
renv::install("bioc::org.Hs.eg.db@3.12.0")
renv::install("bioc::biomaRt")

